# Generated by Django 4.2.5 on 2023-09-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tasks_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='importance',
            field=models.IntegerField(choices=[('low', 'LOW'), ('high', 'HIGH'), ('medium', 'MEDIUM')], default='medium', max_length=6),
        ),
    ]
