# Generated by Django 4.2.5 on 2023-10-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_tasks_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='importance',
            field=models.CharField(choices=[('low', 'LOW'), ('medium', 'MEDIUM'), ('high', 'HIGH')], default='medium', max_length=6),
        ),
    ]
