# Generated by Django 4.2.5 on 2023-10-02 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0005_alter_tasks_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='importance',
            field=models.CharField(choices=[('low', 'LOW'), ('high', 'HIGH'), ('medium', 'MEDIUM')], default='medium', max_length=6),
        ),
    ]
